[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "polars_to_ibis"
authors = [{name = "Chuck McCallum", email = "info@opendp.org"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]
dependencies = [
    "ibis",
    "polars",
]

[project.urls]
Home = "https://github.com/opendp/polars-to-ibis"

[project.optional-dependencies]
app = [
    "ibis==3.3.0",
    "polars-runtime-32==1.34.0",
    "polars==1.34.0",
]
