[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "polars_to_ibis"
authors = [{name = "The OpenDP Project", email = "info@opendp.org"}]
readme = "README-PYPI.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version", "description"]
dependencies = [
    "ibis",
    "polars",
]

[project.urls]
Home = "https://github.com/opendp/polars-to-ibis"

[options]
python_requires = ">=3.10"

[project.optional-dependencies]
app = [
    "ibis==3.3.0",
    "polars-runtime-32==1.34.0",
    "polars==1.34.0",
]

[tool.pyright]
include = ["dp_wizard"]

[tool.isort]
profile = "black"
