LITERAL = "Literal"
COLUMN = "Column"
CAST = "Cast"
SUM = "Sum"
AGG = "Agg"
FUNCTION = "Function"
BINARY_EXPR = "BinaryExpr"

IR = "IR"
SCAN = "Scan"
DATA_FRAME_SCAN = "DataFrameScan"
SELECT = "Select"
FILTER = "Filter"
SLICE = "Slice"
SORT = "Sort"
H_STACK = "HStack"
GROUP_BY = "GroupBy"
MAP_FUNCTION = "MapFunction"
