name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-14 # So DB startup works the same in CI as locally.
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.13'
        polars-version:
          # See setup.cfg for the pinned Polars version:
          # https://github.com/opendp/opendp/blob/stable/python/setup.cfg
          # If this library has wider usage, we can add intermediate versions.
          - '1.32.0' # OpenDP v0.14.1
          - '1.36.1' # OpenDP v0.15.1
          # NOTE: Update README ("Limitations") if there are changes.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start databases
        run: scripts/setup.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      # This may override the version in requirements.
      # TODO: Use tox to manage environments locally and in CI.
      # https://github.com/opendp/polars-to-ibis/issues/40
      - name: Install polars ${{ matrix.polars-version }}
        run: pip install polars==${{ matrix.polars-version }}

      - name: Test
        run: scripts/ci.sh
