name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-14 # So DB startup works the same in CI as locally.
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        polars-version:
          # See setup.cfg for the pinned Polars version:
          # https://github.com/opendp/opendp/blob/stable/python/setup.cfg
          # If this library has wider usage, we can test intermediate versions.
          - '1.32.0' # OpenDP v0.14.1
          - '1.36.1' # OpenDP v0.15.1
          - '1.41.2' # Latest release
          # NOTE: Update README ("Limitations") if there are changes.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start databases
        run: scripts/setup.sh

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.24"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        # TODO: Add "--locked": Was failing with:
        # > The lockfile at `uv.lock` needs to be updated, but `--locked` was provided.
        # > To update the lockfile, run `uv lock`.
        # Running "uv lock" produces no changes.
        run: uv sync --all-extras --dev

      - name: Install polars ${{ matrix.polars-version }}
        run: uv pip install polars==${{ matrix.polars-version }}

      - name: Test
        run: uv run scripts/ci.sh
