name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-14 # So DB startup works the same in CI as locally.
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.13'
        polars-version:
          # We're using OpenDP to exercise Polars plugins.
          # (The point of this project for us is to use OpenDP Polars plugin, after all!
          # Using OpenDP is also easier than trying to build a toy plugin just for testing.)
          # OpenDP v0.14.1 pins Polars to 1.32.0:
          # https://github.com/opendp/opendp/blob/v0.14.1/python/setup.cfg#L52
          - '1.32.0'
          # However, except for Polars plugins, we want the rest of polars-to-ibis
          # to work with higher versions of Polars.
          # (OpenDP will probably pin to a higher version at some point,
          # so we should be ready.)
          - '1.33.0'
          - '1.34.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start databases
        run: scripts/setup.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      # This may override the version in requirements.
      # TODO: Use tox to manage environments locally and in CI.
      # https://github.com/opendp/polars-to-ibis/issues/40
      - name: Install polars ${{ matrix.polars-version }}
        run: pip install polars==${{ matrix.polars-version }}

      - name: Test
        run: scripts/ci.sh
